apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: hobbyin-master
  name: hobbyin-master
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hobbyin-master:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/MaxHXie/hobbyin-master/'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Source
status:
  lastVersion: 1
