from external_page.models import Hobby, Instructor

def populate_database():
    piano = Hobby.objects.create(hobby_name="piano")
    flygning = Hobby.objects.create(hobby_name="flygning")
    malning = Hobby.objects.create(hobby_name="målning")
    schack = Hobby.objects.create(hobby_name="schack")
    tennis = Hobby.objects.create(hobby_name="tennis")

    instructor1 = Instructor.objects.create(first_name="Jan", last_name="Ofjorsson", email="janofh@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=False, maximum_students=2)
    instructor1.hobbies.add(piano, malning)
    instructor2 = Instructor.objects.create(first_name="Olof", last_name="Avoani", email="olav@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=3)
    instructor2.hobbies.add(schack, flygning)
    instructor3 = Instructor.objects.create(first_name="Krister", last_name="Naubasir", email="krinau@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=True, maximum_students=2)
    instructor3.hobbies.add(flygning)
    instructor4 = Instructor.objects.create(first_name="Björn", last_name="Wargas", email="bjwa@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=3)
    instructor4.hobbies.add(tennis)
    instructor5 = Instructor.objects.create(first_name="Johan", last_name="Losa", email="jola@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=True, maximum_students=2)
    instructor5.hobbies.add(piano, malning)
    instructor6 = Instructor.objects.create(first_name="Karl", last_name="Buigan", email="kabu@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=2)
    instructor6.hobbies.add(malning)
    instructor7 = Instructor.objects.create(first_name="Johannes", last_name="Taida", email="jotai@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=False, maximum_students=4)
    instructor7.hobbies.add(flygning, tennis)
    instructor8 = Instructor.objects.create(first_name="Birger", last_name="Tyroler", email="bityr@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=10)
    instructor8.hobbies.add(piano, schack, malning)
    instructor9 = Instructor.objects.create(first_name="Tyko", last_name="Braams", email="tybra@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=1)
    instructor9.hobbies.add(schack)
    instructor10 = Instructor.objects.create(first_name="Charles", last_name="Gorbalov", email="chago@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=True, maximum_students=2)
    instructor10.hobbies.add(piano, flygning)
    instructor11 = Instructor.objects.create(first_name="Karl", last_name="Jansson", email="kajo@kth.se", gender="M", work_in_student_home=True, work_in_instructor_home=False, maximum_students=2)
    instructor11.hobbies.add(malning, tennis)
    instructor12 = Instructor.objects.create(first_name="Moses", last_name="Andersson", email="moand@kth.se", gender="M", work_in_student_home=False, work_in_instructor_home=True, maximum_students=5)
    instructor12.hobbies.add(malning, flygning)
